# -*- coding: utf-8 -*-
"""Travelers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E6PYXzrPIkIgNst7SdelE2G__PNFPreX
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install pandas

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Travelers/Training_TriGuard.csv')
df.head(10)

df_sub = df[df.subrogation == 1]
df_nosub = df[df.subrogation == 0]

cols = df.columns
print(cols)

categorical_vars = [
    "subrogation",
    "gender",
    "email_or_tel_available",
    "high_education_ind",
    "address_change_ind",
    "living_status",
    "zip_code",
    "claim_day_of_week",
    "accident_site",
    "witness_present_ind",
    "channel",
    "policy_report_filed_ind",
    "vehicle_category",
    "vehicle_color",
    "accident_type",
    "in_network_bodyshop"
]

numerical_vars = [
    "claim_number",
    "year_of_born",
    "safety_rating",
    "annual_income",
    "past_num_of_claims",
    "liab_prct",
    "claim_est_payout",
    "vehicle_made_year",
    "vehicle_price",
    "vehicle_weight",
    "age_of_DL",
    "vehicle_mileage"
]

for col in categorical_vars:
    print("=" * 60)
    print(f"🔹 Column: {col}\n")

    # Value counts (absolute counts)
    sub_counts = df_sub[col].value_counts(dropna=False)
    nosub_counts = df_nosub[col].value_counts(dropna=False)
    total_counts = df[col].value_counts(dropna=False)

    # Ratios (percentage of total)
    sub_ratio = sub_counts / len(df_sub)
    nosub_ratio = nosub_counts / len(df_nosub)
    total_ratio = total_counts / len(df)

    # Print results

    print("📌 Subrogation = 1")
    print(pd.DataFrame({"count": sub_counts, "ratio": sub_ratio.round(3)}))
    print()

    print("📌 Subrogation = 0")
    print(pd.DataFrame({"count": nosub_counts, "ratio": nosub_ratio.round(3)}))
    print("\n")

    print("📌 Total")
    print(pd.DataFrame({"count": total_counts, "ratio": total_ratio.round(3)}))
    print("=" * 60)
    print()

for col in numerical_vars:
    print("=" * 70)
    print(f"🔹 Numerical Column: {col}\n")

    print("📌 Subrogation = 1 (df_sub)")
    print(df_sub[col].describe())
    print()

    print("📌 Subrogation = 0 (df_nosub)")
    print(df_nosub[col].describe())
    print()

    print("📌 Full Dataset (df)")
    print(df[col].describe())
    print("\n")

import matplotlib.pyplot as plt
import seaborn as sns

def plot_distribution(col):
    plt.figure(figsize=(12, 5))

    # KDE plot
    plt.subplot(1, 2, 1)
    sns.kdeplot(df_sub[col], label="Subrogation = 1", fill=True, alpha=0.5)
    sns.kdeplot(df_nosub[col], label="Subrogation = 0", fill=True, alpha=0.5)
    plt.title(f"KDE Plot: {col}")
    plt.legend()

    # Boxplot
    plt.subplot(1, 2, 2)
    sns.boxplot(data=df, x="subrogation", y=col)
    plt.title(f"Boxplot: {col}")

    plt.tight_layout()
    plt.show()

for col in numerical_vars:
    plot_distribution(col)

def plot_categorical(col):
    plt.figure(figsize=(10, 5))

    # proportion per category
    overall_ratio = df[col].value_counts(normalize=True)
    sub_ratio     = df_sub[col].value_counts(normalize=True)
    nosub_ratio   = df_nosub[col].value_counts(normalize=True)

    # Build a new DataFrame with groups on x-axis
    ratio_df = pd.DataFrame({
        "No Sub": nosub_ratio,
        "Sub": sub_ratio,
        "Total": overall_ratio
    }).fillna(0)

    # Transpose so x-axis = group names
    ratio_df = ratio_df.T   # rows: groups, columns: categories

    # Plot
    ratio_df.plot(kind="bar", figsize=(10, 5))
    plt.title(f"Category Proportions for: {col}")
    plt.ylabel("Proportion")
    plt.xticks(rotation=0)
    plt.legend(title="Category", bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.tight_layout()
    plt.show()

for col in categorical_vars:
    plot_categorical(col)

"""# Important Numerical Columns

## Most Important
Liab-Pct

### Maybe Important
Vehicle Price, Past number of Claims
They had a different in peak spike

# Important Categorical Columns

## Most Important
Accident cite, Witness Present, Accident type

### Maybe Important
In network body shop, living status, higher education, gender

## Must be careful not to overfit on the training as they will probably put false ideas in the training
"""

